apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2-helm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-2-helm
  template:
    metadata:
      labels:
        app: myapp-2-helm
    spec:
      containers:
      - name: myapp-container
        image: alexholovatskyi/myapp-v2:latest
        ports:
        - containerPort: 8080
